language: python

sudo: false

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

services:
  - xvfb

install:
  - pip install pip -U
  - pip install tox-travis
  - pip install coveralls

script:
  - tox

after_success:
  - coveralls
