# Django version: Supported python versions
#
# 4.2: 3.9, 3.10, 3.11, 3.12
# 5.2: 3.10, 3.11, 3.12, 3.13

[tox]
envlist =
    py39-4.2.X,
    py310-{4.2,5.2}.X,
    py311-{4.2,5.2}.X,
    py312-{4.2,5.2}.X,
    py313-5.2.X,
    py313-coverage,
    docs

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[testenv]
passenv = DISPLAY
deps =
    4.2.X: Django>=4.2,<5.0
    5.2.X: Django>=5.2,<6.0
    Jinja2
    selenium
commands = {envpython} runtests.py

[testenv:py313-coverage]
passenv = DISPLAY
commands = coverage run runtests.py
           coverage report -m --fail-under 80
deps = coverage>=4
       Django>=5.2,<6.0
       Jinja2
       selenium

[testenv:docs]
basepython = python3.10
deps = Sphinx==4.3.0
       caktus-sphinx-theme==0.1.0
commands = {envbindir}/sphinx-build -a -n -b html -d docs/_build/doctrees docs docs/_build/html
