# Generated by Django 5.2.9 on 2026-01-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scribbler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scribble",
            name="content_scheduled",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Temporary content to be displayed during a scheduled time period.",
                verbose_name="Scheduled content",
            ),
        ),
        migrations.AddField(
            model_name="scribble",
            name="content_scheduled_end",
            field=models.DateTimeField(
                blank=True,
                help_text="The end time for displaying the scheduled content. Leave blank for unlimited time.",
                null=True,
                verbose_name="Scheduled content end",
            ),
        ),
        migrations.AddField(
            model_name="scribble",
            name="content_scheduled_start",
            field=models.DateTimeField(
                blank=True,
                help_text="The start time for displaying the scheduled content. This is required for scheduled content to be displayed.",
                null=True,
                verbose_name="Scheduled content start",
            ),
        ),
    ]
